package memory

import (
	"fmt"
	"strings"
)

// CompactResult holds the summary generated by compaction.
type CompactResult struct {
	Summary   string
	FactCount int
}

// Compact extracts facts from the store and builds a summary string.
// Returns the summary text for optional LLM refinement.
func Compact(store *Store) CompactResult {
	facts := store.List(contextCategory)
	summary := buildFactSummary(facts)
	return CompactResult{
		Summary:   summary,
		FactCount: len(facts),
	}
}

// WriteSummary stores a compacted summary back to the store.
func WriteSummary(store *Store, summary string) {
	if summary != "" {
		_ = store.Set("ctx:summary", summary, contextCategory)
	}
}

// buildFactSummary creates a text representation of context facts grouped by type.
func buildFactSummary(facts []Fact) string {
	if len(facts) == 0 {
		return ""
	}

	var files, edits, errors, cmds, other []string
	for _, f := range facts {
		switch classifyFact(f.Key) {
		case contextFile:
			path := f.Key
			if after, ok2 := strings.CutPrefix(path, "ctx:file:"); ok2 {
				path = after
			} else if after, ok2 := strings.CutPrefix(path, "ctx:search:"); ok2 {
				path = after
			}
			files = append(files, path)
		case contextEdit:
			path := strings.TrimPrefix(f.Key, "ctx:edit:")
			edits = append(edits, path+": "+firstLine(f.Value))
		case contextError:
			errors = append(errors, firstLine(f.Value))
		case contextCmd:
			cmds = append(cmds, firstLine(f.Value))
		case contextSummary:
			// Skip existing summaries
		default:
			other = append(other, f.Key+": "+firstLine(f.Value))
		}
	}

	var b strings.Builder
	if len(files) > 0 {
		fmt.Fprintf(&b, "Files read: %s\n", strings.Join(files, ", "))
	}
	if len(edits) > 0 {
		b.WriteString("Edits:\n")
		for _, e := range edits {
			fmt.Fprintf(&b, "  - %s\n", e)
		}
	}
	if len(errors) > 0 {
		b.WriteString("Errors encountered:\n")
		for _, e := range errors {
			fmt.Fprintf(&b, "  - %s\n", e)
		}
	}
	if len(cmds) > 0 {
		b.WriteString("Commands:\n")
		for _, c := range cmds {
			fmt.Fprintf(&b, "  - %s\n", c)
		}
	}
	if len(other) > 0 {
		b.WriteString("Other:\n")
		for _, o := range other {
			fmt.Fprintf(&b, "  - %s\n", o)
		}
	}

	// Append machine-parseable file tracking tags for cumulative tracking
	// across compaction boundaries.
	if len(files) > 0 {
		b.WriteByte('\n')
		writeXMLTagBlock(&b, "read-files", files)
		b.WriteByte('\n')
	}
	if len(edits) > 0 {
		editPaths := make([]string, len(edits))
		for i, e := range edits {
			path, _, _ := strings.Cut(e, ":")
			editPaths[i] = strings.TrimSpace(path)
		}
		b.WriteByte('\n')
		writeXMLTagBlock(&b, "modified-files", editPaths)
		b.WriteByte('\n')
	}

	return b.String()
}

func firstLine(s string) string {
	line, _, _ := strings.Cut(s, "\n")
	r := []rune(line)
	if len(r) > 100 {
		return string(r[:100]) + "..."
	}
	return line
}

// contextCounts holds categorized counts of context facts.
type contextCounts struct {
	files, edits, errors, cmds int
}

// countContextFacts categorizes context facts by key prefix.
func countContextFacts(facts []Fact) contextCounts {
	var c contextCounts
	for _, f := range facts {
		switch classifyFact(f.Key) {
		case contextFile:
			c.files++
		case contextEdit:
			c.edits++
		case contextError:
			c.errors++
		case contextCmd:
			c.cmds++
		}
	}
	return c
}
